name: Run unittests

on: [push, pull_request]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]  # 3.9 not supported on numba as of 2020-02-11
    steps:
    - name: Checkout PyAutoConf
      uses: actions/checkout@v2
      with:
        path: PyAutoConf
    - name: Install dependencies
      run: |
        pip install wheel
        pip install pytest
        pip install -r PyAutoConf/requirements.txt
    - name: Run tests
      run: |
        pushd PyAutoConf
        python3 -m pytest
